#!/usr/bin/env node
// Render a human-readable STATE.md from STATE.json. Run in repo root.
import { readFileSync } from "fs";

const s = JSON.parse(readFileSync("STATE.json", "utf8"));

const when = new Date().toISOString();
const sorted = [...s.entries].sort((a, b) => Number(b.marketCapOZC) - Number(a.marketCapOZC));

const table = sorted.map(e =>
  `| ${e.id} | ${(e.title || "").replace(/\|/g, "\\|")} | ${e.claim_type || ""} | ${Number(e.marketCapOZC).toFixed(4)} | ${e.shareSupply} |`
).join("\n");

const total = sorted.reduce((a, e) => a + Number(e.marketCapOZC), 0);
const active = sorted.filter(e => Number(e.shareSupply) > 1).length;

process.stdout.write(`# OZC State

Generated at: ${when}

- Network: ${s.network}
- Registry: ${s.registry}
- Total claims: ${s.count}
- Claims with third-party backing: ${active}
- Total collected signal: ${total.toFixed(4)} OZC

## Claims by collected signal

| id | title | type | signal (OZC) | units |
|----|-------|------|--------------|-------|
${table}

---
Automatically generated by \`.github/workflows/status-report.yml\`.
`);
